// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using clean.Data;

#nullable disable

namespace clean.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("clean.Dominio.Models.Categoria", b =>
                {
                    b.Property<int>("Id_Categoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Categoria"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("codigoCategoria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id_Categoria");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("clean.Dominio.Models.Producto", b =>
                {
                    b.Property<int>("Id_Producto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Producto"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Precio")
                        .HasColumnType("double precision");

                    b.Property<string>("codigoProducto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id_Producto");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("clean.Dominio.Models.Producto_Categoria", b =>
                {
                    b.Property<int>("Id_Producto_Categoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Producto_Categoria"));

                    b.Property<int?>("Id_Categoria")
                        .HasColumnType("integer");

                    b.Property<int?>("Id_Producto")
                        .HasColumnType("integer");

                    b.Property<int>("categoria_id")
                        .HasColumnType("integer");

                    b.Property<int>("producto_id")
                        .HasColumnType("integer");

                    b.HasKey("Id_Producto_Categoria");

                    b.HasIndex("Id_Categoria");

                    b.HasIndex("Id_Producto");

                    b.ToTable("Producto_Categorias");
                });

            modelBuilder.Entity("clean.Dominio.Models.Producto_Categoria", b =>
                {
                    b.HasOne("clean.Dominio.Models.Categoria", "categoria")
                        .WithMany("productos")
                        .HasForeignKey("Id_Categoria");

                    b.HasOne("clean.Dominio.Models.Producto", "producto")
                        .WithMany("categorias")
                        .HasForeignKey("Id_Producto");

                    b.Navigation("categoria");

                    b.Navigation("producto");
                });

            modelBuilder.Entity("clean.Dominio.Models.Categoria", b =>
                {
                    b.Navigation("productos");
                });

            modelBuilder.Entity("clean.Dominio.Models.Producto", b =>
                {
                    b.Navigation("categorias");
                });
#pragma warning restore 612, 618
        }
    }
}
